services:
  guzzle_client:
    class: GuzzleHttp\Client

  animal_provider:
    class: TimeInc\CatsVsDogsBundle\AnimalProvider\Giphy\GiphyProvider
    arguments:
      - @guzzle_client
      - %time_inc.cats_vs_dogs.api_key%
